spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trips-database/trips
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
