POST {{baseUrl}}/users
Content-Type: application/json

{"firstName": "Jan", "lastName": "Kowalski"}

###

GET {{baseUrl}}/users/2
Accept: application/json

###

POST {{baseUrl}}/api/v1/authentication-service/users
Content-Type: application/json

{"firstName": "Jan", "lastName": "Kowalski"}

###

GET {{baseUrl}}/api/v1/authentication-service/users/2
Accept: application/json

###

POST {{baseUrl}}/api/v1/trips-service/drivers/1/trips
Accept: application/json


###

GET {{baseUrl}}/api/v1/trips-service/trips/3
Accept: application/json

###